### ISSUE TITLE
请问一下，并行测试要怎么处理啊？？？

### ISSUE THREAD

**Issue by songyy137222** [hirorogithub/CaffeWebApi#1]

**Comment by hirorogithub** [comment]
我很久没有碰这一块了，如果只需要单纯的并行运行的话，可以在使用caffe的代码里set_gpu之类的，这个你在代码里找找看，应该是有的。但如果你想网页也支持并行的话估计就有点麻烦了

**Comment by songyy137222** [comment]
对的，我是网页支持并行，也就是很多人可以调用这个网页

**Comment by hirorogithub** [comment]
那样的话，flask本身是不支持并发的，是串行的。简单点的话，可以引入gevent来实现并发。但是感觉更科学的做法应该是flask+nginx/uwsgi之类的服务器

**Comment by songyy137222** [comment]
我刚试了一下gevent可以基本实现网页并行，但它一秒内只能运行80个，如果我想要效果更好的话，是不是需要flask+nginx/uwsgi

**Comment by hirorogithub** [comment]
你需要gpu，你可以直接调用稍微封装后的那个算法接口，看看你的机器一秒能跑多少张。机器学习的东西多半压力在算法，传统的服务端问题应该还轮不到。

**Comment by songyy137222** [comment]
奥，就是说根本还是看算法运行速度，我的程序gpu运行的话一张图大概是500ms

**Comment by hirorogithub** [comment]
是的，基本上瓶颈在算法本身。算法这边有足够机器跑了，或者你换成更新的caffe2之类的，没有优化空间了再去搞服务器这边的请求优化吧。

**Comment by songyy137222** [comment]
好的，谢谢大神指导 ！！！

**Comment by hirorogithub** [comment]
其实你真想搞的话，建议你还是看看新的caffe性能，我这个代码也只不过是官方样例的处理流程拿出来用而已。如果你要用的是那个cascade detect的话，那你还是看看别的模型吧，这个其实也蛮旧的了，虽然也算好用。这几年ML进化很快，我也只是刚好那个时间段玩过一下。这些代码都是挺“过时”的。
